# Use CentOS 9 as the base image
FROM remote-host

# Copy the NGINX repository configuration
COPY ./conf/nginx.repo /etc/yum.repos.d/nginx.repo

# Install NGINX and other dependencies
RUN \
  yum -y install nginx openssl && \
  yum -y install epel-release && \
  yum -y install \
    php-fpm \
    php-cli \
    php-mysqlnd \
    php-soap \
    php-xml \
    php-zip \
    php-json \
    php-mbstring \
    php-gd && \
  yum clean all


RUN mkdir -p /run/php-fpm && chown -R root:root /run/php-fpm && chmod 755 /run/php-fpm && php-fpm

# Expose ports
EXPOSE 80 443

# Volumes
VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm

# Copy the NGINX configuration
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the start script
COPY ./bin/start.sh /start.sh

# Make the start script executable
RUN chmod +x /start.sh

# Set the default command
CMD ["/start.sh"]
